wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.16
    start_time: 1704016835.013053
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 15
      - 23
      4: 3.9.16
      5: 0.13.10
      8:
      - 2
      - 5
